### PR TITLE
Enable heterogeneous inflow in `FlorisStandin`

### PR DESCRIPTION
**Pull request by misi9170**
This pull request provides the ability to provide a heterogeneous inflow, such as one measured at a site or generated by a LES simulator, to be used as inflow data to the `FlorisStandin` wind farm model.

To do list:
- [X] Implement main code
- [X] Create example
- [X] Current tests pass (locally, discussion in #109 and [this comment in particular](https://github.com/NREL/hercules/pull/109#issuecomment-2258917405))
- [x] New tests added
- [x] Documentation updated

### CODE REVIEW

**Comment by misi9170** [comment]
@genevievestarke This is now ready for review. It could be worth testing with the data on Kestrel to check there aren't any snags before merging.

**Comment by misi9170** [comment]
(tests pass locally)

**Comment by genevievestarke** [comment]
Is there a heterogeneous wind input csv file for the example? I don't see it in the example folder, maybe you forgot to override the csv exemption?

**Comment by misi9170** [comment]
> Is there a heterogeneous wind input csv file for the example? I don't see it in the example folder, maybe you forgot to override the csv exemption?

Sorry about that @genevievestarke ! I forgot to exclude the input csv from the .gitignore and then didn't notice it was missing from the repo. That's corrected now. In future, to avoid this issue, it could be nice for data files like this to be stored in a separate subdirectory of example_case_folders/ that we can put a wild card exclusion for in the .gitignore. I started going down that path in fixing the current problem, but decided to wait and implement a more complete fix in future if we decide to go with something like suggested in #113 .

Anyway, hopefully the example can now be run.

**Comment by misi9170** [comment]
> This looks good, and I was able to run it! Are there any post processing files you have to look at the outputs, by any chance?

I don't, but I could put a short script together?

**Comment by genevievestarke** [comment]
No worries, we can add that after the milestone

**Pull request merged**
