### PR TITLE
Citation file

### PR DESCRIPTION
**Pull request by ZackTully**
#73

### CODE REVIEW

**Comment by misi9170** [comment]
Just noting here that I think the citation button won't go into affect until develop is merged into main. An option would be to point this PR at NREL:main instead, which should not create any complications with later merging develop into main (or if it does, they will be easy to manage). @genevievestarke any opinions on that?

**Comment by genevievestarke** [comment]
Sounds good to me!  I think it might be easier to push this file to main, and then merge back into develop?

**Review by genevievestarke — APPROVED** [review]

**Comment by misi9170** [comment]
> Sounds good to me! I think it might be easier to push this file to main, and then merge back into develop?

Ok; I think to do that, the best way will be for me to check out this file on main; push directly to main; merge main into develop; and push develop. This PR will remain open during that process, but once that is done, I can "merge" this PR to show it's completion (although, at that point, there should be no difference between develop and this PR).

**Comment by misi9170** [comment]
I've now directly pushed CITATION.cff to main [ca4fcda](https://github.com/NREL/hercules/commit/ca4fcda0bc1fe7754bc8ddd4c57be0bb3ee10c39), and then merged main back into develop [f598a1a](https://github.com/NREL/hercules/commit/f598a1ac916bcef417d10c98fb0618dcf6d59968). To avoid mucking up the history, I'm closing this PR _without_ merging, and will then close #86.

**Pull request closed without merging**
