### PR TITLE
simple_battery unit tests

### LINKED ISSUE #53: Add pysim battery model tests

### PR DESCRIPTION
**Pull request by ZackTully**
Unit tests for `SimpleBattery` module.

Resolves #53

### CODE REVIEW

**Review by misi9170 — APPROVED** [review]
This is great, thanks for doing this @ZackTully ! If it's not too much to ask, would you do something similar for the HerculesWindBatteryController in WHOC? I already have a placeholder for that [here](https://github.com/NREL/wind-hybrid-open-controller/blob/develop/tests/controller_library_test.py#L114). I also have some ideas for cleaning up the HerculesWindBatteryController a bit, but it would be great to have the tests in place before I/we do that

**Comment by ZackTully** [comment]
@misi9170 Sure! I'll take a look at it later today.

**Review by genevievestarke — APPROVED** [review]
It looks good to me, I'm just wondering why all the floris changes also show up as changed files for this pull request?  Is it because of the Floris v4 update?

**Comment by misi9170** [comment]
> It looks good to me, I'm just wondering why all the floris changes also show up as changed files for this pull request? Is it because of the Floris v4 update?

That's a bit strange... I'll look into that a little, thanks for pointing that out @genevievestarke

**Comment by misi9170** [comment]
@ZackTully @genevievestarke Ok that issues with the comparison is fixed. I'm going to review the [corresponding PR on WHOC](https://github.com/NREL/wind-hybrid-open-controller/pull/28/files) and then should be able to merge both.

**Comment by misi9170** [comment]
@ZackTully Thanks for the updates; I'm going to go ahead and merge this and the companion on WHOC.

**Pull request merged**
